import 'package:flutter/material.dart';
import '../formatters/currency_formatter.dart';
import '../formatters/date_formatter.dart';
import '../theme/app_theme.dart';
import 'package:shared_models/shared_models.dart';

/// Presentational row widget for a single transaction.
///
/// Displays: colored circular icon, name, "category · date" subtitle,
/// and a signed amount (income=green +, expense=red −).
///
/// When [isRecurring] is true, a small repeat badge is overlaid on the
/// leading icon to indicate the entry was generated by a recurring template.
class TransactionRow extends StatelessWidget {
  const TransactionRow({
    super.key,
    required this.name,
    required this.categoryLabel,
    required this.date,
    required this.amountCents,
    required this.transactionType,
    this.isRecurring = false,
    this.recurringDetail,
    this.onDelete,
  });

  final String name;
  final String categoryLabel;
  final DateTime date;
  final int amountCents;
  final TransactionType transactionType;

  /// When true, a recurrence badge (repeat icon) is overlaid on the leading
  /// avatar to indicate the entry was generated by an active recurring template.
  final bool isRecurring;

  /// When non-null, renders the recurrence detail (e.g. "Día 15 de cada mes")
  /// as a small label below the repeat icon in the leading area.
  final String? recurringDetail;

  /// If non-null, a delete icon button is shown on the trailing side.
  final VoidCallback? onDelete;

  bool get _isIncome => transactionType == TransactionType.income;

  Color get _color =>
      _isIncome ? AppColors.income : AppColors.expense;

  @override
  Widget build(BuildContext context) {
    final amountText = CurrencyFormatter.format(
      amountCents,
      isIncome: _isIncome,
    );
    final subtitle = '$categoryLabel · ${DateFormatter.format(date)}';

    Widget avatar = CircleAvatar(
      backgroundColor: _color.withValues(alpha: 0.15),
      child: Icon(
        _isIncome ? Icons.arrow_upward : Icons.arrow_downward,
        color: _color,
        semanticLabel: _isIncome ? 'Ingreso' : 'Gasto',
      ),
    );

    if (isRecurring) {
      avatar = Stack(
        clipBehavior: Clip.none,
        children: [
          avatar,
          Positioned(
            bottom: 0,
            right: 0,
            child: Icon(
              Icons.repeat,
              size: 14,
              color: _color,
              semanticLabel: 'Recurrente',
            ),
          ),
        ],
      );
    }

    final fullSubtitle = (isRecurring && recurringDetail != null)
        ? '$subtitle · $recurringDetail'
        : subtitle;

    return ListTile(
      leading: avatar,
      title: Text(
        name,
        style: const TextStyle(color: AppColors.onBackground),
        overflow: TextOverflow.ellipsis,
      ),
      subtitle: Text(
        fullSubtitle,
        style: const TextStyle(color: AppColors.onBackgroundMuted, fontSize: 12),
      ),
      trailing: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            amountText,
            style: TextStyle(
              color: _color,
              fontWeight: FontWeight.bold,
              fontSize: 14,
            ),
          ),
          if (onDelete != null) ...[
            const SizedBox(width: 8),
            IconButton(
              icon: const Icon(Icons.delete_outline),
              color: AppColors.danger,
              tooltip: 'Eliminar',
              onPressed: onDelete,
            ),
          ],
        ],
      ),
    );
  }
}
