import 'package:drift/drift.dart';
import '../app_database.dart';
import '../tables/transactions.dart';
import '../tables/recurring_templates.dart';

part 'transaction_dao.g.dart';

/// Result type returned by [TransactionDao.watchFilteredWithTemplateStatus].
///
/// - [templateIsDeleted] == null  → one-off transaction (no template)
/// - [templateIsDeleted] == false → generated by an active recurring template
/// - [templateIsDeleted] == true  → generated by a now-cancelled template
typedef TransactionWithStatus = ({
  TransactionRow transaction,
  bool? templateIsDeleted,
});

@DriftAccessor(tables: [Transactions])
class TransactionDao extends DatabaseAccessor<AppDatabase>
    with _$TransactionDaoMixin {
  TransactionDao(super.db);

  Future<int> insert(TransactionsCompanion entry) =>
      into(transactions).insert(entry);

  /// Most recent [limit] transactions, ordered by date DESC.
  Stream<List<TransactionRow>> watchRecent({int limit = 10}) {
    return (select(transactions)
          ..orderBy([(t) => OrderingTerm.desc(t.date)])
          ..limit(limit))
        .watch();
  }

  /// All transactions, ordered by date DESC.
  Stream<List<TransactionRow>> watchAll() {
    return (select(transactions)
          ..orderBy([(t) => OrderingTerm.desc(t.date)]))
        .watch();
  }

  /// Transactions within the given date range, ordered by date DESC.
  Stream<List<TransactionRow>> watchFiltered({
    required DateTime start,
    required DateTime end,
  }) {
    return (select(transactions)
          ..where((t) => t.date.isBetweenValues(start, end))
          ..orderBy([(t) => OrderingTerm.desc(t.date)]))
        .watch();
  }

  /// Transactions within [months] calendar months back from now.
  Stream<List<TransactionRow>> watchMonthly({required int months}) {
    final now = DateTime.now();
    final start = DateTime(now.year, now.month - months + 1, 1);
    return watchFiltered(start: start, end: now);
  }

  Future<int> deleteById(int id) {
    return (delete(transactions)..where((t) => t.id.equals(id))).go();
  }

  /// Transactions within [start, end] with their recurring status resolved via
  /// a LEFT JOIN to [RecurringTemplates], ordered by date DESC.
  ///
  /// Use this provider to determine whether a transaction's recurrence badge
  /// should be shown. The [templateIsDeleted] field of each result indicates:
  /// - null  → no template (one-off entry, no badge)
  /// - false → active template (show recurrence badge)
  /// - true  → cancelled template (no badge, entries still preserved)
  Stream<List<TransactionWithStatus>> watchFilteredWithTemplateStatus({
    required DateTime start,
    required DateTime end,
  }) {
    final query = select(transactions).join([
      leftOuterJoin(
        db.recurringTemplates,
        db.recurringTemplates.id.equalsExp(transactions.templateId),
      ),
    ])
      ..where(transactions.date.isBetweenValues(start, end))
      ..orderBy([OrderingTerm.desc(transactions.date)]);

    return query.watch().map(
      (rows) => rows
          .map(
            (row) => (
              transaction: row.readTable(transactions),
              templateIsDeleted:
                  row.readTableOrNull(db.recurringTemplates)?.isDeleted,
            ),
          )
          .toList(),
    );
  }
}
