import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_services/shared_services.dart';
import 'package:shared_ui/shared_ui.dart' hide TransactionRow;
import 'package:shared_models/shared_models.dart';
import '../domain/time_range.dart';
import 'dao_providers.dart';

/// Display model for a single transaction row in the UI.
class TransactionDisplay {
  const TransactionDisplay({
    required this.id,
    required this.name,
    required this.categoryLabel,
    required this.date,
    required this.amountCents,
    required this.transactionType,
    required this.iconColor,
    required this.isRecurring,
    this.templateId,
  });

  final int id;
  final String name;
  final String categoryLabel;
  final DateTime date;
  final int amountCents;
  final TransactionType transactionType;
  final Color iconColor;

  /// True when this entry was generated by an active recurring template.
  /// False for one-off entries or entries whose template has been cancelled.
  final bool isRecurring;

  /// The originating template id, or null for one-off entries.
  final int? templateId;
}

/// Maps a raw [TransactionRow] to a UI-ready [TransactionDisplay].
///
/// [templateIsDeleted]: from a LEFT JOIN to RecurringTemplates.
/// - null  → one-off entry → isRecurring = false
/// - false → active template → isRecurring = true
/// - true  → cancelled template → isRecurring = false
TransactionDisplay _toDisplay(TransactionRow row, {bool? templateIsDeleted}) {
  final isIncome = row.transactionType == 'income';
  final type = isIncome ? TransactionType.income : TransactionType.expense;
  final color = isIncome ? AppColors.income : AppColors.expense;

  String label;
  if (isIncome) {
    final cat = IncomeCategory.values.where((c) => c.name == row.category).firstOrNull;
    label = cat?.displayLabel ?? row.category;
  } else {
    final cat = ExpenseCategory.values.where((c) => c.name == row.category).firstOrNull;
    label = cat?.displayLabel ?? row.category;
  }

  return TransactionDisplay(
    id: row.id,
    name: row.name,
    categoryLabel: label,
    date: row.date,
    amountCents: row.amountCents,
    transactionType: type,
    iconColor: color,
    isRecurring: row.templateId != null && templateIsDeleted == false,
    templateId: row.templateId,
  );
}

/// Most recent 10 transactions for the Resumen view. No delete affordance.
final recentTransactionsProvider =
    StreamProvider<List<TransactionDisplay>>((ref) {
  return ref
      .watch(transactionDaoProvider)
      .watchRecent(limit: 10)
      .map((rows) => rows.map((r) => _toDisplay(r)).toList());
});

/// All transactions matching a [DateTimeRange] for filtering views (Análisis).
/// Does not resolve recurring status — not needed outside of Entradas.
final filteredTransactionsProvider =
    StreamProvider.family<List<TransactionDisplay>, DateTimeRange>(
  (ref, range) {
    return ref
        .watch(transactionDaoProvider)
        .watchFiltered(start: range.start, end: range.end)
        .map((rows) => rows.map((r) => _toDisplay(r)).toList());
  },
);

/// Selected time range for the unified Entradas view.
/// Replaces the old setState usage in TransaccionesTab.
final selectedTimeRangeProvider =
    StateProvider<TimeRange>((ref) => TimeRange.ultimos7Dias);

/// All entries (one-off + recurring-generated) for the unified Entradas view,
/// with [TransactionDisplay.isRecurring] correctly derived via a LEFT JOIN
/// to RecurringTemplates. Ordered by date DESC.
final unifiedEntriesProvider =
    StreamProvider.family<List<TransactionDisplay>, DateTimeRange>(
  (ref, range) {
    return ref
        .watch(transactionDaoProvider)
        .watchFilteredWithTemplateStatus(start: range.start, end: range.end)
        .map(
          (rows) => rows
              .map(
                (e) => _toDisplay(
                  e.transaction,
                  templateIsDeleted: e.templateIsDeleted,
                ),
              )
              .toList(),
        );
  },
);
