import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_ui/shared_ui.dart';
import '../../providers/dao_providers.dart';
import '../../providers/transaction_providers.dart';
import '../analisis/time_range_selector.dart';

/// Unified Entradas view — single chronological list of all entries.
///
/// Both one-off transactions and entries generated by recurring templates are
/// shown together. Recurring entries display a recurrence badge. Delete actions
/// are differentiated: recurring entries cancel the template (with an
/// explanatory dialog), one-off entries are permanently removed.
class EntradasView extends ConsumerWidget {
  const EntradasView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final selectedRange = ref.watch(selectedTimeRangeProvider);
    final dateRange = selectedRange.toDateRange();
    final entriesAsync = ref.watch(
      unifiedEntriesProvider(
        DateTimeRange(start: dateRange.start, end: dateRange.end),
      ),
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.all(16),
          child: TimeRangeSelector(
            selected: selectedRange,
            onChanged: (r) =>
                ref.read(selectedTimeRangeProvider.notifier).state = r,
          ),
        ),
        const Divider(color: AppColors.surfaceVariant, height: 1),
        Expanded(
          child: entriesAsync.when(
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) => const Center(
              child: Text(
                'Error al cargar entradas',
                style: TextStyle(color: AppColors.expense),
              ),
            ),
            data: (entries) {
              if (entries.isEmpty) {
                return const Center(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Text(
                      'Sin entradas para este período.',
                      style: TextStyle(color: AppColors.onBackgroundMuted),
                      textAlign: TextAlign.center,
                    ),
                  ),
                );
              }
              return ListView.separated(
                itemCount: entries.length,
                separatorBuilder: (_, __) =>
                    const Divider(color: AppColors.surfaceVariant, height: 1),
                itemBuilder: (_, i) {
                  final entry = entries[i];
                  return TransactionRow(
                    name: entry.name,
                    categoryLabel: entry.categoryLabel,
                    date: entry.date,
                    amountCents: entry.amountCents,
                    transactionType: entry.transactionType,
                    isRecurring: entry.isRecurring,
                    onDelete: entry.isRecurring
                        ? () => _confirmDeleteRecurring(context, ref, entry)
                        : () => _confirmDeleteOneOff(context, ref, entry),
                  );
                },
              );
            },
          ),
        ),
      ],
    );
  }

  Future<void> _confirmDeleteRecurring(
    BuildContext context,
    WidgetRef ref,
    TransactionDisplay entry,
  ) async {
    final confirmed = await showConfirmationDialog(
      context: context,
      title: 'Cancelar entrada recurrente',
      message: 'Se cancelará la programación de "${entry.name}". '
          'No se generarán nuevas entradas en el futuro. '
          'Esta entrada y todas las anteriores generadas por esta '
          'programación se conservan.',
      confirmLabel: 'Cancelar programación',
      cancelLabel: 'Volver',
    );
    if (confirmed) {
      await ref.read(templateDaoProvider).softDelete(entry.templateId!);
    }
  }

  Future<void> _confirmDeleteOneOff(
    BuildContext context,
    WidgetRef ref,
    TransactionDisplay entry,
  ) async {
    final confirmed = await showConfirmationDialog(
      context: context,
      title: 'Eliminar transacción',
      message: '¿Eliminar "${entry.name}"? Esta acción no se puede deshacer.',
      confirmLabel: 'Eliminar',
      cancelLabel: 'Cancelar',
    );
    if (confirmed) {
      await ref.read(transactionDaoProvider).deleteById(entry.id);
    }
  }
}
