import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_ui/shared_ui.dart';
import '../../domain/category_filter.dart';
import '../../providers/transaction_providers.dart';
import '../analisis/time_range_selector.dart';
import 'category_filter_selector.dart';

/// Unified Entradas view — single chronological list of all entries.
///
/// Both one-off transactions and entries generated by recurring templates are
/// shown together. Recurring entries display a recurrence badge.
/// Entries cannot be deleted from this view; deletion is only available
/// in the Recurrentes view for recurring templates.
///
/// Supports two combined filters: time range and category.
/// Both filters reset to their defaults when the view is disposed.
class EntradasView extends ConsumerStatefulWidget {
  const EntradasView({super.key});

  @override
  ConsumerState<EntradasView> createState() => _EntradasViewState();
}

class _EntradasViewState extends ConsumerState<EntradasView> {
  @override
  void initState() {
    super.initState();
    // Reset category filter to "Todas" each time the view is entered,
    // fulfilling FR-008 (filter resets when leaving the view).
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        ref.read(selectedCategoryFilterProvider.notifier).state =
            CategoryFilter.all;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final selectedRange = ref.watch(selectedTimeRangeProvider);
    final selectedCategory = ref.watch(selectedCategoryFilterProvider);
    final entriesAsync = ref.watch(filteredEntriesProvider);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TimeRangeSelector(
                selected: selectedRange,
                onChanged: (r) =>
                    ref.read(selectedTimeRangeProvider.notifier).state = r,
              ),
              const SizedBox(height: 8),
              CategoryFilterSelector(
                selected: selectedCategory,
                onChanged: (c) =>
                    ref.read(selectedCategoryFilterProvider.notifier).state = c,
              ),
            ],
          ),
        ),
        const Divider(color: AppColors.surfaceVariant, height: 1),
        Expanded(
          child: entriesAsync.when(
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) => const Center(
              child: Text(
                'Error al cargar entradas',
                style: TextStyle(color: AppColors.expense),
              ),
            ),
            data: (entries) {
              if (entries.isEmpty) {
                return const Center(
                  child: Padding(
                    padding: EdgeInsets.all(32),
                    child: Text(
                      'Sin entradas para este período.',
                      style: TextStyle(color: AppColors.onBackgroundMuted),
                      textAlign: TextAlign.center,
                    ),
                  ),
                );
              }
              return ListView.separated(
                itemCount: entries.length,
                separatorBuilder: (_, __) =>
                    const Divider(color: AppColors.surfaceVariant, height: 1),
                itemBuilder: (_, i) {
                  final entry = entries[i];
                  return TransactionRow(
                    name: entry.name,
                    categoryLabel: entry.categoryLabel,
                    date: entry.date,
                    amountCents: entry.amountCents,
                    transactionType: entry.transactionType,
                    isRecurring: entry.isRecurring,
                    recurringDetail: entry.recurringDetail,
                  );
                },
              );
            },
          ),
        ),
      ],
    );
  }
}
